name: ci-cd pipeline

on:
  push:
    branches:
      - github-actions

jobs: 
  buildApp: 
    name: Build Next.js app
    runs-on: ubuntu-latest
    steps: 
    - id: step1
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test
